version: '1.0.{build}'
skip_branch_with_pr: true
image: Visual Studio 2017
install:
  - dotnet --version
build_script:
  - ps: .\ci_build.ps1
artifacts:
  - path: '**/*.nupkg'
    name: NuGet Packages
